export const defaultCategoryNames = [
  "Food",
  "Transport",
  "Housing",
  "Utilities",
  "Health",
  "Insurance",
  "Entertainment",
  "Education",
  "Shopping",
  "Salary",
  "Freelance",
  "Investments",
  "Gifts",
  "Travel",
  "Other",
] as const
